### ISSUE TITLE
Maven down

### ISSUE THREAD

**Issue by confuser** [timbru31/updater#28]
It seems https://repo.dustplanet.de is down. Not sure if you're aware, if so, will it be available again?

**Comment by timbru31** [comment]
Yeah, I'm currently migrating my whole server. Should be up again soon. In the meanwhile, feel free to mirror the artifact. The latest release is here: https://ci.dustplanet.de/job/updater/60/

**Comment by timbru31** [comment]
Artifact v4.0.0 has been restored. I will upload the older versions, once the server migration is finished.

**Comment by timbru31** [comment]
My Artifactory instance seems to crash after some duration - I'll re-open this issue.

**Comment by SimonIT** [comment]
Any progress?
